
apiVersion: v1
kind: Service
metadata:
  name: ozone-datanode-public-public
  labels:
    app: ozone
    component: datanode
spec:
  ports:
  - port: 9870
    name: rpc
  selector:
    app: ozone
    component: datanode
  type: NodePort
