
apiVersion: v1
kind: Service
metadata:
  name: ozone-recon-public-public
  labels:
    app: ozone
    component: recon
spec:
  ports:
  - port: 9888
    name: ui
  selector:
    app: ozone
    component: recon
  type: NodePort
