
apiVersion: v1
kind: Service
metadata:
  name: ozone-scm
  labels:
    app: ozone
    component: scm
spec:
  ports:
  - port: 9876
    name: ui
  clusterIP: None
  selector:
    app: ozone
    component: scm
