
apiVersion: v1
kind: Service
metadata:
  name: ozone-datanode
  labels:
    app: ozone
    component: datanode
spec:
  ports:
  - port: 9870
    name: rpc
  clusterIP: None
  selector:
    app: ozone
    component: datanode
