
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-s3g
  labels:
    app: ozone
    component: s3g
spec:
  selector:
    matchLabels:
      app: ozone
      component: s3g
  serviceName: ozone-s3g
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: s3g
    spec:
      containers:
      - name: s3g
        image: ghcr.io/elek/ozone-dev:159b0c61c
        args:
        - ozone
        - s3g
        volumeMounts:
        - name: data
          mountPath: /data
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        hostPath:
          path: /data1
      initContainers: []
