
apiVersion: v1
kind: Service
metadata:
  name: ozone-recon
  labels:
    app: ozone
    component: recon
spec:
  ports:
  - port: 9888
    name: ui
  clusterIP: None
  selector:
    app: ozone
    component: recon
