
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-recon
  labels:
    app: ozone
    component: recon
spec:
  selector:
    matchLabels:
      app: ozone
      component: recon
  serviceName: ozone-recon
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: recon
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9888"
        prometheus.io/path: /prom
    spec:
      containers:
      - name: recon
        image: ghcr.io/elek/ozone-dev:f5e1fcadc
        args:
        - ozone
        - recon
        volumeMounts:
        - name: data
          mountPath: /data
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        hostPath:
          path: /data
      initContainers: []
