
apiVersion: v1
kind: Service
metadata:
  name: ozone-s3g
  labels:
    app: ozone
    component: s3g
spec:
  ports:
  - port: 9878
    name: rest
  clusterIP: None
  selector:
    app: ozone
    component: s3g
