
apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode
  labels:
    app: hdfs
    component: datanode
spec:
  ports:
  - port: 9874
    name: web
  clusterIP: None
  selector:
    app: hdfs
    component: datanode
