
apiVersion: v1
kind: Service
metadata:
  name: ozone-om
  labels:
    app: ozone
    component: om
spec:
  ports:
  - port: 9874
    name: ui
  clusterIP: None
  selector:
    app: ozone
    component: om
