apiVersion: v1
kind: Pod
metadata:
  name: ozone-replicator
  labels:
    app: ozone
    component: replicator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9882"
    prometheus.io/path: /prom
spec:
  restartPolicy: Never
  nodeSelector:
    placement: replicator
  securityContext:
    fsGroup: 1000
  containers:
  - name: replicator
    image: localhost:32100/elek/ozone-dev:93e61f21d
    args:
    - ozone
    - freon
    - cr
    - -t
    - '80'
    volumeMounts:
    - name: data
      mountPath: /data
    envFrom:
    - configMapRef:
        name: ozone-config
    env:
      - name: OZONE_CONF_DIR
        value: /opt/ozone/etc/hadoop
  volumes:
  - name: data
    hostPath:
      path: /data
