# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: dataconfig
description: Configure data directory
---
- type: Add
  trigger:
    metadata:
      name: ozone-config
  path:
    - data
  value:
    OZONE-SITE.XML_hdds.datanode.dir: /data/disk2/elek,/data/disk3/elek,/data/disk4/elek,/data/disk5/elek,/data/disk6/elek,/data/disk7/elek,/data/disk8/elek,/data/disk9/elek,/data/disk10/elek,/data/disk11/elek,/data/disk12/elek,/data/disk13/elek,/data/disk14/elek,/data/disk15/elek,/data/disk16/elek,/data/disk17/elek,/data/disk18/elek,/data/disk19/elek,/data/disk20/elek,/data/disk21/elek,/data/disk22/elek,/data/disk23/elek,/data/disk24/elek,/data/disk25/elek,/data/disk26/elek,/data/disk27/elek,/data/disk28/elek,/data/disk29/elek,/data/disk30/elek,/data/disk31/elek,/data/disk32/elek,/data/disk33/elek,/data/disk34/elek,/data/disk35/elek,/data/disk36/elek,/data/disk37/elek,/data/disk38/elek,/data/disk39/elek,/data/disk40/elek,/data/disk41/elek,/data/disk42/elek,/data/disk43/elek,/data/disk44/elek,/data/disk45/elek,/data/disk46/elek,/data/disk47/elek,/data/disk48/elek
    OZONE-SITE.XML_ozone.scm.datanode.id.dir: /data/disk1/elek
    OZONE-SITE.XML_ozone.metadata.dirs: /data/disk1/elek