
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-datanode
  labels:
    app: ozone
    component: datanode
spec:
  selector:
    matchLabels:
      app: ozone
      component: datanode
  serviceName: ozone-datanode
  replicas: 3
  template:
    metadata:
      labels:
        app: ozone
        component: datanode
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9882"
        prometheus.io/path: /prom
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - datanode
              - key: app
                operator: In
                values:
                - ozone
            topologyKey: kubernetes.io/hostname
      securityContext:
        fsGroup: 1000
      containers:
      - name: datanode
        image: localhost:32100/elek/ozone-dev:159fb248a
        args:
        - ozone
        - freon
        - cgdn
        - -n
        - "20480"
        - -t
        - "48"
        volumeMounts:
        - name: data
          mountPath: /data
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        hostPath:
          path: /data
      nodeSelector:
        placement: datanode
